version: '3'
services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: npm start
    # Environment variables, database links, etc.

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm start
    # Link to backend service if necessary
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
